### ISSUE TITLE
allow clients to control error behavior

### ISSUE THREAD

**Issue by alexdean** [PRX/amara#5]
```ruby
client = Amara::Client.new
client.videos.create({})
```

This raises an error, and i have no idea how to find out what actually went wrong - even though the raw response from Amara does include debugging information. I'd like to be able to receive a response object even when my request results in an error.

I think it would be relatively straightforward to implement `create!` alongside the existing `create`. (Similar bang methods could be created for `get`, `update`, `delete`, etc.)

The only difference would be that the bang versions raise an exception when Amara returns a non-200 response, while the non-bang versions always return an `Amara::Response` instance. Using the non-bang versions, the client would be able to look at the response and get the troubleshooting information they need.

@kookster Would you be open to a PR that adds this feature? I expect it would require a major version bump, since the behavior of non-bang methods (like `create`) would change substantially. But the upgrade path would be very simple - add a `!` if you want to keep old behavior.

**Comment by kookster** [comment]
more discussion is in the #6 PR

**Comment by kookster** [comment]
released in 0.3.0
